name = "Hexed"
author = "Fozimus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8eabd5a7a0c8cf49163784bea9f7924e970972c20e26cb939b5f9df0453c442"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"
