name = "Hexed"
author = "Fozimus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68caf547f01a2d580a5d9a984f8f3515e382dba652afebd62564907775a5bf12"

[versions]
fabric = "0.19.5"
minecraft = "1.20.1"
